enum GhostPrefix {
  GENERIC = "any-prefix",

  CURSOR = "cursor",
  CARET_COLOR = "caret",
  ACCENT_COLOR = "accent",
  POINTER_EVENTS = "pointer-events",
  SCROLL_BEHAVIOR = "scroll",
  RESIZE = "resize",
  USER_SELECT = "user-select",

  TRANSITION = "transition",
  TRANSITION_DELAY = "delay",
  TRANSITION_DURATION = "duration",
  TRANSITION_PROPERTY = "transition-p",
  TRANSITION_TIMING_FUNCTION = "timing-function",

  MATRIX = "matrix",
  MATRIX_3D = "matrix-3d",
  TRANSLATE = "translate",
  TRANSLATE_3D = "translate-3d",
  TRANSLATE_X = "translate-x",
  TRANSLATE_Y = "translate-y",
  TRANSLATE_Z = "translate-z",
  SCALE = "scale",
  SCALE_3D = "scale-3d",
  SCALE_X = "scale-x",
  SCALE_Y = "scale-y",
  SCALE_Z = "scale-z",
  ROTATE = "rotate",
  ROTATE_3D = "rotate-3d",
  ROTATE_X = "rotate-x",
  ROTATE_Y = "rotate-y",
  ROTATE_Z = "rotate-z",
  SKEW = "skew",
  SKEW_X = "skew-x",
  SKEW_Y = "skew-y",
  PERSPECTIVE = "perspective",

  BG_COLOR = "bg",
  BG_ATTACHMENT = "bg-attach",
  BG_BLEND = "bg-blend",
  BG_CLIP = "bg-clip",
  BG_ORIGIN = "bg-origin",
  BG_POSITION = "bg-pos",
  BG_REPEAT = "bg-repeat",
  BG_SIZE = "bg-size",

  COLOR = "txt",
  FONT_WEIGHT = "txt-weight",
  FONT_SIZE = "txt-size",
  FONT_STYLE = "txt-style",
  FONT_VARIANT = "txt-variant",
  FONT_VARIANT_CAPS = "txt-variant-caps",
  TEXT_DECORATION = "decoration",
  TEXT_DECORATION_COLOR = "decoration-c",
  TEXT_DECORATION_LINE = "decoration-l",
  TEXT_DECORATION_STYLE = "decoration-s",
  TEXT_DECORATION_THICKNESS = "decoration-t",
  TEXT_OVERFLOW = "txt-overflow",
  TEXT_SHADOW = "txt-shadow",
  TEXT_ALIGN = "txt-align",
  FONT_FAMILY = "font",
  LETTER_SPACING = "tracking",
  LINE_HEIGHT = "leading",
  LIST_STYLE_TYPE = "list-type",

  DISPLAY = "d",
  POSITION = "pos",
  TOP = "top",
  BOTTOM = "bottom",
  RIGHT = "right",
  LEFT = "left",
  BOX = "box",
  FLOAT = "float",
  CLEAR = "clear",
  OBJECT_FIT = "object",
  OVERFLOW = "overflow",
  OVERFLOW_Y = "overflow-y",
  OVERFLOW_X = "overflow-x",
  OVERSCROLL = "overscroll",
  OVERSCROLL_X = "overscroll-x",
  OVERSCROLL_Y = "overscroll-y",
  VISIBILITY = "visibility",

  FLEX_BASIS = "basis",
  FLEX_DIRECTION = "fd",
  FLEX_WRAP = "fw",
  FLEX_GROW = "grow",
  FLEX_SHRINK = "shrink",

  GRID_TEMPLATE_COLUMNS = "cols",
  GRID_COLUMN_SPAN = "col-span",
  GRID_COLUMN_START = "col-start",
  GRID_COLUMN_END = "col-end",
  GRID_TEMPLATE_ROWS = "rows",
  GRID_ROW_SPAN = "row-span",
  GRID_ROW_START = "row-start",
  GRID_ROW_END = "row-end",
  GRID_FLOW = "grid-flow",
  GRID_AUTO_COLUMNS = "auto-columns",
  GRID_AUTO_ROWS = "auto-rows",

  GAP = "gap",
  COLUMN_GAP = "gap-x",
  ROW_GAP = "gap-y",
  ORDER = "order",
  JUSTIFY_CONTENT = "justify",
  JUSTIFY_ITEMS = "justify-items",
  JUSTIFY_SELF = "justify-self",
  ALIGN_CONTENT = "align",
  ALIGN_ITEMS = "align-items",
  ALIGN_SELF = "align-self",
  PLACE_CONTENT = "place",
  PLACE_ITEMS = "place-items",
  PLACE_SELF = "place-self",

  WIDTH = "w",
  HEIGHT = "h",
  MIN_WIDTH = "min-w",
  MIN_HEIGHT = "min-h",
  MAX_WIDTH = "max-w",
  MAX_HEIGHT = "max-h",

  PADDING = "p",
  PADDING_RIGHT = "pr",
  PADDING_LEFT = "pl",
  PADDING_BOTTOM = "pb",
  PADDING_TOP = "pt",
  PADDING_X = "px",
  PADDING_Y = "py",

  MARGIN = "m",
  MARGIN_RIGHT = "mr",
  MARGIN_LEFT = "ml",
  MARGIN_BOTTOM = "mb",
  MARGIN_TOP = "mt",
  MARGIN_X = "mx",
  MARGIN_Y = "my",

  SPACE_X = "space-x",
  SPACE_Y = "space-y",

  BORDER = "border",
  BORDER_RIGHT = "border-r",
  BORDER_LEFT = "border-l",
  BORDER_TOP = "border-t",
  BORDER_BOTTOM = "border-b",
  BORDER_Y = "border-y",
  BORDER_X = "border-x",
  DIVIDE_Y = "divide-y",
  DIVIDE_X = "divide-x",
  BORDER_RADIUS = "rounded",

  OUTLINE = "outline",
  OUTLINE_WIDTH = "outline-w",
  OUTLINE_OFFSET = "outline-o",
  OUTLINE_STYLE = "outline-s",
  OUTLINE_COLOR = "outline-c",

  Z_INDEX = "z",
}

export default GhostPrefix;