enum PropertyCSS {
  GENERIC = "any-property",

  CURSOR = "cursor",
  CARET_COLOR = "caret-color",
  ACCENT_COLOR = "accent-color",
  POINTER_EVENTS = "pointer-events",
  SCROLL_BEHAVIOR = "scroll-behavior",
  RESIZE = "resize",
  USER_SELECT = "user-select",

  TRANSITION = "transition",
  TRANSITION_DELAY = "transition-delay",
  TRANSITION_DURATION = "transition-duration",
  TRANSITION_PROPERTY = "transition-property",
  TRANSITION_TIMING_FUNCTION = "transition-timing-function",

  TRANSFORM = "transform",

  BG_COLOR = "background-color",
  BG_ATTACHMENT = "background-attachment",
  BG_BLEND = "background-blend-mode",
  BG_CLIP = "background-clip",
  BG_ORIGIN = "background-origin",
  BG_POSITION = "background-position",
  BG_REPEAT = "background-repeat",
  BG_SIZE = "background-size",

  COLOR = "color",
  FONT_WEIGHT = "font-weight",
  FONT_SIZE = "font-size",
  FONT_STYLE = "font-style",
  FONT_VARIANT = "font-variant",
  FONT_VARIANT_CAPS = "font-variant-caps",
  TEXT_DECORATION = "text-decoration",
  TEXT_DECORATION_COLOR = "text-decoration-color",
  TEXT_DECORATION_LINE = "text-decoration-line",
  TEXT_DECORATION_STYLE = "text-decoration-style",
  TEXT_DECORATION_THICKNESS = "text-decoration-thickness",
  TEXT_OVERFLOW = "text-overflow",
  TEXT_SHADOW = "text-shadow",
  FONT_FAMILY = "font-family",
  TEXT_ALIGN = "text-align",
  LETTER_SPACING = "letter-spacing",
  LINE_HEIGHT = "line-height",
  LIST_STYLE_TYPE = "list-style-type",

  DISPLAY = "display",
  POSITION = "position",
  TOP = "top",
  BOTTOM = "bottom",
  RIGHT = "right",
  LEFT = "left",
  BOX_SIZING = "box-sizing",
  FLOAT = "float",
  CLEAR = "clear",
  OBJECT_FIT = "object-fit",
  OVERFLOW = "overflow",
  OVERFLOW_Y = "overflow-y",
  OVERFLOW_X = "overflow-x",
  OVERSCROLL = "overscroll-behavior",
  OVERSCROLL_X = "overscroll-behavior-x",
  OVERSCROLL_Y = "overscroll-behavior-y",
  VISIBILITY = "visibility",

  FLEX_BASIS = "flex-basis",
  FLEX_DIRECTION = "flex-direction",
  FLEX_WRAP = "flex-wrap",
  FLEX_GROW = "flex-grow",
  FLEX_SHRINK = "flex-shrink",

  GRID_TEMPLATE_COLUMNS = "grid-template-columns",
  GRID_COLUMN_SPAN = "grid-column",
  GRID_COLUMN_START = "grid-column-start",
  GRID_COLUMN_END = "grid-column-end",
  GRID_TEMPLATE_ROWS = "grid-template-rows",
  GRID_ROW_SPAN = "grid-row",
  GRID_ROW_START = "grid-row-start",
  GRID_ROW_END = "grid-row-end",
  GRID_FLOW = "grid-auto-flow",
  GRID_AUTO_COLUMNS = "grid-auto-columns",
  GRID_AUTO_ROWS = "grid-auto-rows",

  GAP = "gap",
  COLUMN_GAP = "column-gap",
  ROW_GAP = "row-gap",
  ORDER = "order",
  JUSTIFY_CONTENT = "justify-content",
  JUSTIFY_ITEMS = "justify-items",
  JUSTIFY_SELF = "justify-self",
  ALIGN_CONTENT = "align-content",
  ALIGN_ITEMS = "align-items",
  ALIGN_SELF = "align-self",
  PLACE_CONTENT = "place-content",
  PLACE_ITEMS = "place-items",
  PLACE_SELF = "place-self",

  WIDTH = "width",
  HEIGHT = "height",
  MIN_WIDTH = "min-width",
  MIN_HEIGHT = "min-height",
  MAX_WIDTH = "max-width",
  MAX_HEIGHT = "max-height",

  PADDING = "padding",
  PADDING_RIGHT = "padding-right",
  PADDING_LEFT = "padding-left",
  PADDING_BOTTOM = "padding-bottom",
  PADDING_TOP = "padding-top",

  MARGIN = "margin",
  MARGIN_RIGHT = "margin-right",
  MARGIN_LEFT = "margin-left",
  MARGIN_BOTTOM = "margin-bottom",
  MARGIN_TOP = "margin-top",

  BORDER = "border",
  BORDER_RIGHT = "border-right",
  BORDER_LEFT = "border-left",
  BORDER_TOP = "border-top",
  BORDER_BOTTOM = "border-bottom",
  BORDER_RADIUS = "border-radius",

  OUTLINE = "outline",
  OUTLINE_WIDTH = "outline-width",
  OUTLINE_OFFSET = "outline-offset",
  OUTLINE_STYLE = "outline-style",
  OUTLINE_COLOR = "outline-color",

  Z_INDEX = "z-index",
}

export default PropertyCSS;